### ISSUE TITLE
Bluetooth forces GPS?

### ISSUE THREAD

**Issue by torantal** [casainho/ketonix_keto_breathalyzer#1]
"the app forces GPS / my location to be enable which does not make sense for a system that just needs to measure my breath acetone"

I think that has to do with how bluetooth is implemented in Android, esp. if it's a BT low-energy device (not sure).

**Comment by casainho** [comment]
Thanks, just corrected it.

I am still using mine sometimes, but I am now using a FreeStyle Libre real time glucose monitor and trying to always get a a low value like 90 or less, which usually means I am on Ketosis.
